### PR TITLE
use req.params

### PR DESCRIPTION
**Pull request by gacord23**

### CODE REVIEW

**Comment by matthewadams** [comment]
The deprecation of `req.param()` is disputed by many, and its use in this context is more flexible than just using `req.params`.  The argument for accepting this PR would be for restriction over flexibility, which, given that the framework should be agnostic toward its uses, is going the wrong way, IMHO.  Others have any thoughts?

**Comment by gacord23** [comment]
This is just because I'm tired of seeing the log at runtime.  If it's a point of discussion, I'm happy to continue ignoring it for now.

**Comment by matthewadams** [comment]
It'd be nice to be able to suppress that warning in express.  Perhaps there's a better solution, where you could specify in the DSL which source(s) to take info from, and in what order, and make the default the same as `req.param()`.

**Comment by jkamke** [comment]
You could... clone the behavior of the deprecated function and put it into
a util. For ease of use you could add a plugin which puts the behavior onto
the request object and exposes it as a function called `req.param()` :)

**Pull request closed without merging**
